name: Run Unit Tests

on: push

jobs:
  unit_test-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Setup node"
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Run tests
        run: |
          yarn install --frozen-lockfile
          yarn test

      - name: Build app
        run: yarn build
        env:
          VITE_GITHUB_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          VITE_GITHUB_REDIRECT_URL: ${{ vars.REDIRECT_URL }}
          VITE_GITHUB_AUTH_URL: ${{ vars.AUTH_URL }}
          VITE_GITHUB_GISTS_API_URL: ${{ vars.GISTS_API_URL }}

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          SOURCE_DIR: dist/
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
